name: Go Linter
on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'

# Following the principle of least privilege
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false
          
      - name: Download dependencies
        run: go mod download
        
      - name: Verify dependencies
        run: go mod verify
        
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: latest
          only-new-issues: true
